/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getAllVouchers } from '../fn/vouchers/get-all-vouchers';
import { GetAllVouchers$Params } from '../fn/vouchers/get-all-vouchers';
import { getVoucherById } from '../fn/vouchers/get-voucher-by-id';
import { GetVoucherById$Params } from '../fn/vouchers/get-voucher-by-id';
import { Vouchers } from '../models/vouchers';

@Injectable({ providedIn: 'root' })
export class VouchersService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllVouchers()` */
  static readonly GetAllVouchersPath = '/api/vouchers';

  /**
   * Get all vouchers.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllVouchers()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllVouchers$Response(params?: GetAllVouchers$Params, context?: HttpContext): Observable<StrictHttpResponse<Vouchers>> {
    return getAllVouchers(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all vouchers.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllVouchers$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllVouchers(params?: GetAllVouchers$Params, context?: HttpContext): Observable<Vouchers> {
    return this.getAllVouchers$Response(params, context).pipe(
      map((r: StrictHttpResponse<Vouchers>): Vouchers => r.body)
    );
  }

  /** Path part for operation `getVoucherById()` */
  static readonly GetVoucherByIdPath = '/api/vouchers/{id}';

  /**
   * get voucher by id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getVoucherById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getVoucherById$Response(params: GetVoucherById$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return getVoucherById(this.http, this.rootUrl, params, context);
  }

  /**
   * get voucher by id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getVoucherById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getVoucherById(params: GetVoucherById$Params, context?: HttpContext): Observable<void> {
    return this.getVoucherById$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
