/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SubmissionItem {
  ContentLength: number;
  ContentType: string;
  CreatedById: number;
  CreatedOn: string;
  FileId: number;
  Height: number;
  Id: number;
  LastModifiedById: number;
  LastModifiedOn: string;
  Orientation: number;
  Rating: number;
  SubmissionId: number;
  ThumbnailId: number;
  Width: number;
}
