/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Vouchers {
  CreatedById: string;
  CreatedOn: string;
  Id: number;
  LastModifiedById: string;
  LastModifiedOn: string;
  SubmissionId: string;
  ValidatedOn: string;
  VoucherCode: string;
  VoucherPrize: string;
  VoucherPrizeEn: string;
  WinningChallengeId: string;
  WorkspaceId: string;
}
