/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Workspace {
  AddressLine1: string;
  AddressLine2: string;
  City: string;
  CompanyDataProtectionUrl: string;
  CompanyName: string;
  CompanyVat: string;
  ContactMail: string;
  ContactPhone: string;
  ContactUrl: string;
  CountryId: number;
  CreatedById: number;
  CreatedOn: string;
  DateOfBirth: string;
  DefaultPrizeId: number;
  Description: string;
  DescriptionEn: string;
  FileId: number;
  FirstName: string;
  HasPassword: boolean;
  Id: number;
  LastModifiedById: number;
  LastModifiedOn: string;
  LastName: string;
  Name: string;
  OwnerId: number;
  Password: string;
  PostalCode: string;
  Slug: string;
  StripeSessionId: string;
  StripeSubscriptionId: string;
  SubscriptionEndDate: string;
  SubscriptionStatus: string;
  TrialEndsOn: string;
  TrialStartOn: string;
  UploadLimit: string;
}
